DROP SCHEMA IF EXISTS "invoice" CASCADE;

CREATE SCHEMA "invoice";


create table if not exists failure_record
(
    id                  bigint generated by default as identity
        primary key,
    error_record        varchar(255),
    exception_record    varchar(255),
    key_record          varchar(255),
    offset_value_record bigint,
    partition_record    integer,
    status              varchar(255),
    topic_record        varchar(255)
);

alter table failure_record
    owner to postgres;

create table if not exists t_events_order_line_items
(
    id           bigint generated by default as identity
        primary key,
    price        numeric(19, 2),
    quantity     integer,
    sku_code     varchar(255),
    total_amount numeric(19, 2)
);

alter table t_events_order_line_items
    owner to postgres;

create table if not exists t_orders_events
(
    id                 bigint generated by default as identity
        primary key,
    created_date       timestamp,
    last_modified_date timestamp,
    order_id           varchar(255),
    order_status       varchar(255),
    user_email         varchar(255),
    user_name          varchar(255)
);

alter table t_orders_events
    owner to postgres;

create table if not exists t_orders_events_order_line_items
(
    order_event_id      bigint not null
        constraint fkgssag93ir5rtajm9aqvl8rpl1
            references t_orders_events,
    order_line_items_id bigint not null
        constraint uk_l1lb8pclf8nb5pyryvbbg9kv7
            unique
        constraint fk1cedqrq48irns0lx3pupwbcmx
            references t_events_order_line_items
);

alter table t_orders_events_order_line_items
    owner to postgres;

